name: GuiShop
main: GuiShop\Main
version: 1.0.0-BETA1
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author: xItzMarcYT
description: ShopUI for servers!
commands:
 shop:
  description: Open Hypervion's ShopUI by xItzMarcYT
